AWSTemplateFormatVersion: 2010-09-09
Parameters:
  DesiredCount:
    Type: Number
    Default: 0
  TargetGroup:
    Type: String
  Cluster:
    Type: String
  Repository:
    Type: String
Resources:

  ApiService:
    Type: 'AWS::ECS::Service'
    DependsOn: ApiListenerRule
    Properties:
      Cluster: !Ref EcsCluster
      DesiredCount: 1
      Role: !Ref EcsServiceRole
      TaskDefinition: !Ref ApiTaskDefinition
      LoadBalancers:
        - ContainerName: api
          ContainerPort: 8080
          TargetGroupArn: !Ref LbApiTargetGroup

  ApiTaskDefinition:
    Type: 'AWS::ECS::TaskDefinition'
    Properties:
      Family: !Join ['', [!Ref 'AWS::StackName', -api]]
      ContainerDefinitions:
        - Name: api
          Cpu: '100'
          Image: !Sub '${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${ApiContainerRegistry}:latest'
          Memory: '1024'
          Environment:
            - Name: 'JAVA_OPTS'
              Value: '-DSERVER_CONTEXT_PATH=/api'
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref 'CloudwatchLogsGroup'
              awslogs-region: !Ref 'AWS::Region'
              awslogs-stream-prefix: 'api'
          PortMappings:
            - ContainerPort: 8080