template_path: templates/devsecops-stack.yaml
parameters:
  AvailabilityZones: us-east-2a,us-east-2b
  GitHubRepo: https://github.com/YOUR_USERNAME/raptor-devops
  GitHubBranch: master
  GitHubToken: YOUR_API_TOKEN
  GitHubUser: YOUR_USERNAME
  AllowedIP: {{ var.allowed_ip_cidr }}
  KeyPair: raptor
  Version: {{ var.version }}